server:
  port: 8100
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gahlawat80/spring-cloud-config
          search-paths:
          - '*service'
  profiles:
    active:
    - dev
